# Generated by Django 6.0 on 2026-01-04 10:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Иҷозат',
                'verbose_name_plural': 'Иҷозатҳо',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Як интихоб'), ('multiple_choice', 'Чанд интихоб'), ('true_false', 'Дурст/Нодуруст')], max_length=20)),
                ('points', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Савол',
                'verbose_name_plural': 'Саволҳо',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Админ'), ('teacher', 'Муаллим'), ('student', 'Талаба'), ('group_leader', 'Сарвари гурӯҳ')], default='student', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Истифодабаранда',
                'verbose_name_plural': 'Истифодабарандагон',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Эҷод'), ('update', 'Навсозӣ'), ('delete', 'Ҳазф'), ('login', 'Воридшавӣ'), ('logout', 'Баромад'), ('attempt', 'Иштирок')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Логи аудит',
                'verbose_name_plural': 'Логҳои аудит',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Гурӯҳ',
                'verbose_name_plural': 'Гурӯҳҳо',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_type', models.CharField(choices=[('school', 'Мактаб'), ('university', 'Донишгоҳ')], default='school', max_length=20, verbose_name='Навъи таҳсил')),
                ('current_level', models.IntegerField(default=1, help_text='Синф (1-11) ё курс (1-4)', verbose_name='Синф/Курс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Корбар')),
            ],
            options={
                'verbose_name': 'Профил',
                'verbose_name_plural': 'Профилҳо',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.question')),
            ],
            options={
                'verbose_name': 'Ҷавоб',
                'verbose_name_plural': 'Ҷавобҳо',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Сарлавҳа')),
                ('description', models.TextField(blank=True, verbose_name='Тавсиф')),
                ('quiz_mode', models.CharField(choices=[('individual', 'Индивидуалӣ'), ('group', 'Гурӯҳӣ')], max_length=20, verbose_name='Реҷаи викторина')),
                ('level_type', models.CharField(choices=[('school', 'Мактаб'), ('university', 'Донишгоҳ')], max_length=20, verbose_name='Навъи сатҳ')),
                ('start_level', models.IntegerField(verbose_name='Сатҳи оғоз')),
                ('end_level', models.IntegerField(verbose_name='Сатҳи анҷом')),
                ('start_time', models.DateTimeField(verbose_name='Вақти оғоз')),
                ('end_time', models.DateTimeField(verbose_name='Вақти анҷом')),
                ('is_online', models.BooleanField(default=True, verbose_name='Онлайн')),
                ('status', models.CharField(choices=[('draft', 'Навишта'), ('published', 'Нашршуда'), ('active', 'Фаъол'), ('finished', 'Анҷомёфта')], default='draft', max_length=20, verbose_name='Статус')),
                ('time_limit', models.IntegerField(default=30, help_text='Дақиқаҳо', verbose_name='Мӯҳлати вақт (дақиқа)')),
                ('max_attempts', models.IntegerField(default=1, help_text='Максимум кӯшишҳо', verbose_name='Максимум кӯшишҳо')),
                ('pass_percentage', models.IntegerField(default=60, help_text='Фоизи гузарондан', verbose_name='Фоиз барои гузарондан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Санаи эҷод')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Эҷодкунанда')),
            ],
            options={
                'verbose_name': 'Викторина',
                'verbose_name_plural': 'Викторинаҳо',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.quiz'),
        ),
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to='core.group')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.quiz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сеанси викторина',
                'verbose_name_plural': 'Сеансҳои викторина',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('user', 'Истифодабаранда'), ('group', 'Гурӯҳ')], max_length=10)),
                ('rank', models.IntegerField()),
                ('score', models.FloatField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.quiz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтингҳо',
                'ordering': ['quiz', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('total_questions', models.IntegerField()),
                ('correct_answers', models.IntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.group')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.quiz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Натиҷа',
                'verbose_name_plural': 'Натиҷаҳо',
                'ordering': ['-score', 'completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('grade_level', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#4361ee', max_length=7)),
                ('icon', models.CharField(default='fas fa-book', max_length=50)),
                ('is_public', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('max_students', models.PositiveIntegerField(default=0)),
                ('pass_percentage', models.PositiveIntegerField(default=60)),
                ('prerequisites', models.TextField(blank=True, null=True)),
                ('level_type', models.CharField(choices=[('school', 'Мактаб'), ('university', 'Донишгоҳ')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Фан',
                'verbose_name_plural': 'Фанҳо',
                'unique_together': {('name', 'level_type')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='core.subject', verbose_name='Фан'),
        ),
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.subject'),
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Аъзои гурӯҳ',
                'verbose_name_plural': 'Аъзои гурӯҳҳо',
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='core.quizsession')),
            ],
            options={
                'verbose_name': 'Ҷавоби истифодабаранда',
                'verbose_name_plural': 'Ҷавобҳои истифодабарандагон',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
