# Generated by Django 6.0 on 2026-01-01 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_level',
            field=models.IntegerField(default=1, help_text='Синф (1-11) ё курс (1-4)', verbose_name='Синф/Курс'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level_type',
            field=models.CharField(choices=[('school', 'Мактаб'), ('university', 'Донишгоҳ')], default='school', max_length=20, verbose_name='Навъи таҳсил'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Корбар'),
        ),
    ]
